services:
  app:
    build: .
    image: payledger:fixed
    ports:
      - "8080:8080"
    environment:
      - DB_DSN=postgres://postgres:postgres@db:5432/transaction_engine?sslmode=disable
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transaction_engine
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
